version: '3'
services:
  qbdev-integration:
    build: .
    network_mode: bridge
    image: qbdev-integration
    container_name: qb-dev-integration-container
    env_file:
      - ./dev.env
    restart: always
    network_mode: bridge
    volumes:
      - .:/app
    logging:
      driver: gcplogs
