version: '3'
services:
  qbdev-integration:
    build: .
    container_name: qb-dev-integration-container
    env_file:
      - ./dev.env
    image: qbdev-integration
    logging:
      driver: gcplogs
    network_mode: bridge
    restart: always
    volumes:
      - .:/app
